language: node_js
git:
        submodules: false
        depth: 999999
node_js:
        - "8"
before_install:
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init --recursive
before_deploy: "npm run gitbook:install && npm run gitbook:build"
deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        on:
                branch: master
        local_dir: ./gh-pages/
        name: aleen42
        email: aleen42@vip.qq.com
